exclude: 'llama.cpp'
repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=120]
        exclude: 'tests|scripts'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        language_version: python3.9
        args: [--config=.flake8]
        exclude: 'tests|scripts'
      - id: check-added-large-files
        args: ['--maxkb=123']
      - id: trailing-whitespace


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--namespace-packages", "--explicit-package-bases"]
        exclude: 'tests|scripts'
        additional_dependencies: ['types-requests']